// Local copy of examples/playground/src/sample-model.ts for editor 5a
// (no shared example package yet). The initial EditorDocument source.
import {
  StandardParameter,
  type IkiModel,
  type IkiWarpGrid,
} from "@iki/format";
import { bakeHeadTurnGridWarp, generateGridMesh } from "./mesh-generator";

/**
 * A hand-authored face built from solid-color quads. Crude on purpose — it
 * exists to prove the parameter -> binding -> transform -> pixels pipeline and
 * to show how a model wires the standard parameters a talking avatar needs.
 */
const SKIN: [number, number, number, number] = [0.98, 0.85, 0.74, 1];
const DARK: [number, number, number, number] = [0.16, 0.16, 0.2, 1];
const LIP: [number, number, number, number] = [0.78, 0.32, 0.36, 1];

// 4x4 RGBA PNG atlas with four solid-color quadrants (generated by /tmp/gen-atlas.mjs):
//   UV [0.0, 0.0, 0.5, 0.5]  -> top-left     -> red
//   UV [0.5, 0.0, 0.5, 0.5]  -> top-right    -> green
//   UV [0.0, 0.5, 0.5, 0.5]  -> bottom-left  -> blue
//   UV [0.5, 0.5, 0.5, 0.5]  -> bottom-right -> yellow
// Top row (red/green) differs from bottom row (blue/yellow) for visible V-flip detection.
const ATLAS =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAGklEQVR42mP4z8DwH4SRIJoAlA8EDGCMIQAAZhYj3eRg21gAAAAASUVORK5CYII=";

// Head mesh: 8×8 grid covering the full ±0.5 local unit frame.
// UV rect spans the whole atlas (head is color-only, no texture is sampled).
const headMesh = generateGridMesh(8, 8, { x: 0, y: 0, width: 1, height: 1 });

// Small meshes for eyes and mouth — 2×2 cells over the full ±0.5 local frame.
const eyeMesh = generateGridMesh(2, 2, { x: 0, y: 0, width: 1, height: 1 });
const mouthMesh = generateGridMesh(2, 2, { x: 0, y: 0, width: 1, height: 1 });

/**
 * Generate (cols+1)*(rows+1) MODEL-space grid control points, row-major.
 * Row 0 is the TOP (y = maxY); y decreases with row index (+y up).
 * Column 0 is left (x = minX); x increases with column index.
 * This ordering satisfies the IkiWarpGrid validator invariant.
 */
function generateGridPoints(
  cols: number,
  rows: number,
  minX: number,
  maxX: number,
  minY: number,
  maxY: number,
): number[] {
  const pts: number[] = [];
  for (let row = 0; row <= rows; row++) {
    const t = row / rows;
    const y = maxY - t * (maxY - minY); // maxY at row 0, minY at row `rows`
    for (let col = 0; col <= cols; col++) {
      const s = col / cols;
      const x = minX + s * (maxX - minX); // minX at col 0, maxX at col `cols`
      pts.push(x, y);
    }
  }
  return pts;
}

// Face warp grid: 4×4 cells (5×5 control points) in MODEL space.
// Spans roughly the head part's face area: x ∈ [-260, 260], y ∈ [-310, 310].
const faceGrid: IkiWarpGrid = {
  cols: 4,
  rows: 4,
  points: generateGridPoints(4, 4, -260, 260, -310, 310),
};
// Cylinder-bend keyforms for the group warp — curvature lives here only;
// the rigid turn/translate stays on headDeformer (no double-apply).
const faceWarp = bakeHeadTurnGridWarp(faceGrid, StandardParameter.AngleX);

export const sampleModel: IkiModel = {
  version: 1,
  name: "Sample Face",
  canvas: { width: 1000, height: 1000 },
  textures: [{ source: ATLAS }],
  parameters: [
    {
      id: StandardParameter.MouthOpen,
      name: "Mouth Open",
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.MouthForm,
      name: "Mouth Form",
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.EyeOpenLeft,
      name: "Eye L",
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: StandardParameter.EyeOpenRight,
      name: "Eye R",
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: StandardParameter.EyeballX,
      name: "Gaze X",
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.EyeballY,
      name: "Gaze Y",
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.AngleX,
      name: "Head Angle",
      min: -30,
      max: 30,
      default: 0,
    },
    {
      id: StandardParameter.Breath,
      name: "Breath",
      min: 0,
      max: 1,
      default: 0,
    },
  ],
  // headDeformer rotates/bobs the whole face as one rigid body about the neck pivot.
  // faceWarp is parented to headDeformer: it adds cylinder-bend curvature on top
  // of the rigid turn. Curvature lives ONLY in faceWarp — no double-apply.
  deformers: [
    {
      id: "headDeformer",
      // Pivot at neck level: model space, y negative = below canvas center.
      pivot: { x: 0, y: -350 },
      bindings: [
        {
          parameter: StandardParameter.AngleX,
          channel: "rotate",
          from: 6,
          to: -6,
        },
        {
          parameter: StandardParameter.AngleX,
          channel: "translateX",
          from: -50,
          to: 50,
        },
        {
          parameter: StandardParameter.Breath,
          channel: "translateY",
          from: 0,
          to: -12,
        },
      ],
    },
    {
      kind: "warp" as const,
      id: "faceWarp",
      parent: "headDeformer",
      grid: faceGrid,
      warps: [faceWarp],
    },
  ],
  parts: [
    {
      id: "head",
      color: SKIN,
      width: 520,
      height: 620,
      order: 0,
      transform: { x: 0, y: 0 },
      // faceWarp (child of headDeformer) supplies cylinder-bend; no per-part warp needed.
      deformer: "faceWarp",
      mesh: headMesh,
    },
    {
      id: "eyeL",
      color: DARK,
      width: 90,
      height: 90,
      order: 2,
      transform: { x: -110, y: 70 },
      // Must carry a mesh because deformer is a warp deformer.
      deformer: "faceWarp",
      mesh: eyeMesh,
      bindings: [
        {
          parameter: StandardParameter.EyeOpenLeft,
          channel: "scaleY",
          from: -0.85,
          to: 0,
        },
        {
          parameter: StandardParameter.EyeballX,
          channel: "translateX",
          from: -25,
          to: 25,
        },
        {
          parameter: StandardParameter.EyeballY,
          channel: "translateY",
          from: -20,
          to: 20,
        },
      ],
    },
    {
      id: "eyeR",
      color: DARK,
      width: 90,
      height: 90,
      order: 2,
      transform: { x: 110, y: 70 },
      // Must carry a mesh because deformer is a warp deformer.
      deformer: "faceWarp",
      mesh: eyeMesh,
      bindings: [
        {
          parameter: StandardParameter.EyeOpenRight,
          channel: "scaleY",
          from: -0.85,
          to: 0,
        },
        {
          parameter: StandardParameter.EyeballX,
          channel: "translateX",
          from: -25,
          to: 25,
        },
        {
          parameter: StandardParameter.EyeballY,
          channel: "translateY",
          from: -20,
          to: 20,
        },
      ],
    },
    {
      id: "mouth",
      color: LIP,
      width: 150,
      height: 34,
      order: 2,
      transform: { x: 0, y: -150 },
      // Must carry a mesh because deformer is a warp deformer.
      deformer: "faceWarp",
      mesh: mouthMesh,
      bindings: [
        {
          parameter: StandardParameter.MouthOpen,
          channel: "scaleY",
          from: 0,
          to: 3,
        },
        {
          parameter: StandardParameter.MouthForm,
          channel: "scaleX",
          from: -0.2,
          to: 0.4,
        },
      ],
    },
    // Badges stay on headDeformer (matrix path), NOT faceWarp — they sit outside
    // the face grid bbox and are implicit textured quads (mesh-required rule only
    // applies when referencing a warp deformer). They ride the rigid turn fine.
    // Textured badge (untinted) — top-left atlas quadrant = red.
    // UV [0,0, 0.5,0.5] is safely inside the quadrant (no seam bleed).
    {
      id: "badge_red",
      color: [1, 1, 1, 1],
      width: 120,
      height: 120,
      order: 3,
      transform: { x: -380, y: 380 },
      texture: { index: 0, uv: { x: 0.05, y: 0.05, width: 0.4, height: 0.4 } },
      deformer: "headDeformer",
    },
    // Textured badge (tinted orange) — bottom-right atlas quadrant = yellow [1,1,0,1],
    // tinted by [1,0.35,0,1] -> result [1,0.35,0,1] ≈ orange, demonstrating per-channel
    // tint multiplication (the green channel is visibly suppressed).
    {
      id: "badge_yellow_tinted",
      color: [1, 0.35, 0, 1],
      width: 120,
      height: 120,
      order: 3,
      transform: { x: 380, y: 380 },
      texture: { index: 0, uv: { x: 0.55, y: 0.55, width: 0.4, height: 0.4 } },
      deformer: "headDeformer",
    },
  ],
};
