import { StandardParameter, type IkiModel } from "@iki/format";

/**
 * A hand-authored face built from solid-color quads. Crude on purpose — it
 * exists to prove the parameter -> binding -> transform -> pixels pipeline and
 * to show how a model wires the standard parameters a talking avatar needs.
 */
const SKIN: [number, number, number, number] = [0.98, 0.85, 0.74, 1];
const DARK: [number, number, number, number] = [0.16, 0.16, 0.2, 1];
const LIP: [number, number, number, number] = [0.78, 0.32, 0.36, 1];

// 4x4 RGBA PNG atlas with four solid-color quadrants (generated by /tmp/gen-atlas.mjs):
//   UV [0.0, 0.0, 0.5, 0.5]  -> top-left     -> red
//   UV [0.5, 0.0, 0.5, 0.5]  -> top-right    -> green
//   UV [0.0, 0.5, 0.5, 0.5]  -> bottom-left  -> blue
//   UV [0.5, 0.5, 0.5, 0.5]  -> bottom-right -> yellow
// Top row (red/green) differs from bottom row (blue/yellow) for visible V-flip detection.
const ATLAS =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAGklEQVR42mP4z8DwH4SRIJoAlA8EDGCMIQAAZhYj3eRg21gAAAAASUVORK5CYII=";

export const sampleModel: IkiModel = {
  version: 1,
  name: "Sample Face",
  canvas: { width: 1000, height: 1000 },
  textures: [{ source: ATLAS }],
  parameters: [
    {
      id: StandardParameter.MouthOpen,
      name: "Mouth Open",
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.MouthForm,
      name: "Mouth Form",
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.EyeOpenLeft,
      name: "Eye L",
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: StandardParameter.EyeOpenRight,
      name: "Eye R",
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: StandardParameter.EyeballX,
      name: "Gaze X",
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.EyeballY,
      name: "Gaze Y",
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: StandardParameter.AngleX,
      name: "Head Angle",
      min: -30,
      max: 30,
      default: 0,
    },
    {
      id: StandardParameter.Breath,
      name: "Breath",
      min: 0,
      max: 1,
      default: 0,
    },
  ],
  // headDeformer rotates/bobs the whole face as one rigid body about the neck pivot.
  // Parts bound to it must NOT duplicate these bindings (double-apply).
  deformers: [
    {
      id: "headDeformer",
      // Pivot at neck level: model space, y negative = below canvas center.
      pivot: { x: 0, y: -350 },
      bindings: [
        {
          parameter: StandardParameter.AngleX,
          channel: "rotate",
          from: 6,
          to: -6,
        },
        {
          parameter: StandardParameter.AngleX,
          channel: "translateX",
          from: -50,
          to: 50,
        },
        {
          parameter: StandardParameter.Breath,
          channel: "translateY",
          from: 0,
          to: -12,
        },
      ],
    },
  ],
  parts: [
    {
      id: "head",
      color: SKIN,
      width: 520,
      height: 620,
      order: 0,
      transform: { x: 0, y: 0 },
      deformer: "headDeformer",
    },
    {
      id: "eyeL",
      color: DARK,
      width: 90,
      height: 90,
      order: 2,
      transform: { x: -110, y: 70 },
      deformer: "headDeformer",
      bindings: [
        {
          parameter: StandardParameter.EyeOpenLeft,
          channel: "scaleY",
          from: -0.85,
          to: 0,
        },
        {
          parameter: StandardParameter.EyeballX,
          channel: "translateX",
          from: -25,
          to: 25,
        },
        {
          parameter: StandardParameter.EyeballY,
          channel: "translateY",
          from: -20,
          to: 20,
        },
      ],
    },
    {
      id: "eyeR",
      color: DARK,
      width: 90,
      height: 90,
      order: 2,
      transform: { x: 110, y: 70 },
      deformer: "headDeformer",
      bindings: [
        {
          parameter: StandardParameter.EyeOpenRight,
          channel: "scaleY",
          from: -0.85,
          to: 0,
        },
        {
          parameter: StandardParameter.EyeballX,
          channel: "translateX",
          from: -25,
          to: 25,
        },
        {
          parameter: StandardParameter.EyeballY,
          channel: "translateY",
          from: -20,
          to: 20,
        },
      ],
    },
    {
      id: "mouth",
      color: LIP,
      width: 150,
      height: 34,
      order: 2,
      transform: { x: 0, y: -150 },
      deformer: "headDeformer",
      bindings: [
        {
          parameter: StandardParameter.MouthOpen,
          channel: "scaleY",
          from: 0,
          to: 3,
        },
        {
          parameter: StandardParameter.MouthForm,
          channel: "scaleX",
          from: -0.2,
          to: 0.4,
        },
      ],
    },
    // Textured badge (untinted) — top-left atlas quadrant = red.
    // UV [0,0, 0.5,0.5] is safely inside the quadrant (no seam bleed).
    {
      id: "badge_red",
      color: [1, 1, 1, 1],
      width: 120,
      height: 120,
      order: 3,
      transform: { x: -380, y: 380 },
      texture: { index: 0, uv: { x: 0.05, y: 0.05, width: 0.4, height: 0.4 } },
      deformer: "headDeformer",
    },
    // Textured badge (tinted orange) — bottom-right atlas quadrant = yellow [1,1,0,1],
    // tinted by [1,0.35,0,1] -> result [1,0.35,0,1] ≈ orange, demonstrating per-channel
    // tint multiplication (the green channel is visibly suppressed).
    {
      id: "badge_yellow_tinted",
      color: [1, 0.35, 0, 1],
      width: 120,
      height: 120,
      order: 3,
      transform: { x: 380, y: 380 },
      texture: { index: 0, uv: { x: 0.55, y: 0.55, width: 0.4, height: 0.4 } },
      deformer: "headDeformer",
    },
  ],
};
