export {
  EditorDocument,
  type AtlasAssignment,
  type ApplyAtlasInput,
} from "./document";
export {
  AddDeformer,
  AddPart,
  AddPhysicsRig,
  CaptureGridKeyform,
  DeleteDeformer,
  DeletePart,
  DeletePhysicsRig,
  SetDeformerBindings,
  SetDeformerParent,
  SetDeformerPivot,
  SetDeformerPivotX,
  SetDeformerPivotY,
  SetDeformerTransform,
  SetPartBindings,
  SetPartColor,
  SetPartDeformer,
  SetPartMesh,
  SetPartHeight,
  SetPartOrder,
  SetPartTransform,
  SetPartWidth,
  SetPhysicsRig,
  type DeformerTransformChannel,
  type EditCommand,
  type EditTransformChannel,
} from "./commands";
export {
  ALPHA_BBOX_THRESHOLD,
  detectAlphaBbox,
  type AlphaBbox,
} from "./alpha-bbox";
export {
  ALPHA_OPAQUE,
  HEAD_BAND,
  SPECK_CORE_FRACTION,
  createLayerSetMeasurer,
  denseCoreOf,
  foregroundSpan,
  headHalfOf,
  isSpeckCore,
  type LayerSetMeasurement,
  type LayerSetMeasurer,
  type RgbaLayer,
} from "./layer-measure";
export { captureBindingEndpoint } from "./binding-capture";
export {
  computeGridOffsets,
  interpolateGridOffsets,
  upsertGridKeyform,
} from "./grid-keyform";
export {
  packAtlas,
  uvRectFor,
  ATLAS_PADDING,
  UV_INSET_PX,
  type AtlasSource,
  type AtlasPlacement,
  type AtlasLayout,
} from "./atlas";
export {
  validateDeformerDelete,
  validateDeformerReparent,
  validatePartAttach,
} from "./reparent";
export {
  createDefaultPart,
  createDefaultMatrixDeformer,
  createDefaultWarpDeformer,
  createGridMesh,
} from "./factories";
export {
  DEFAULT_TURN_TARGETS,
  LayerGeometryError,
  LIP_INSIDE_ROLES,
  LIP_ROLES,
  TurnTargetError,
  armGeometry,
  columnRuns,
  forearmPoseGeometry,
  generateIkiFromLayerSet,
  isLipInsideRole,
  mouthFold,
  mouthOpening,
  mouthRestShift,
  parseLayerRoles,
  partIdsOfRole,
  type ArmGeometry,
  type ForearmPoseGeometry,
  type IrisStrand,
  type LayerInput,
  type LipInsideRole,
  type LipRole,
  type Opening,
  type OpeningColumn,
  type RigStyle,
  type StrandOverlap,
  type TurnDepths,
  type TurnSolveReport,
  type TurnTargets,
} from "./auto-rig";
